### ISSUE TITLE
The sync directory icon is being uploaded

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#72]
Not sure if this is a big deal or not, but just so you know. If its not a problem please close this issue.

```
[Thread-1] DEBUG org.dizitart.no2.Nitrite - Unsaved changes committed successfully.
[Thread-1] INFO  io.goobox.sync.storj.UploadFileTask - Uploading file desktop.ico
[Thread-1] INFO  io.goobox.sync.storj.UploadFileTask -     0%               0/0 bytes
[Thread-1] INFO  io.goobox.sync.storj.UploadFileTask -     4%           16384/370070 bytes
[Thread-1] INFO  io.goobox.sync.storj.UploadFileTask -    17%           65536/370070 bytes
[Thread-1] INFO  io.goobox.sync.storj.UploadFileTask -    22%           81920/370070 bytes
[Thread-1] INFO  io.goobox.sync.storj.UploadFileTask -    26%           98304/370070 bytes
[Thread-1] INFO  io.goobox.sync.storj.UploadFileTask -    30%          114688/370070 bytes
[Thread-2] DEBUG io.methvin.watcher.DirectoryWatcher - Registering [C:\Users\meije\Goobox].
[Thread-1] INFO  io.goobox.sync.storj.UploadFileTask -   100%          370070/370070 bytes
```

**Comment by jkawamoto** [comment]
It's intended for now. At some point, `desktop.ico` would be excluded to be uploaded.

**Comment by kaloyan-raev** [comment]
@jkawamoto Why is it intended?

**Comment by jkawamoto** [comment]
Since `desktop.ico` isn't a system file generally and [Utils.isExcluded](https://github.com/GooBox/goobox-sync-common/blob/62bb33e6212aece1cf3dc147446e4979a900922b/src/main/java/io/goobox/sync/common/Utils.java#L102) doesn't exclude it. Later, we can add `desktop.ico` in the root of sync folder to the excluded files, though. 

I'll open a related issue in [goobox-sync-common](https://github.com/GooBox/goobox-sync-common) and close this.
