### ISSUE TITLE
Used storage scale bar exceeds defined spectrum 

### ISSUE THREAD

**Issue by foximulder** [GooBox/goobox-community-gui#93]
Ive copied 31Gb to the Goobox-folder after few seconds Goobox shows me usage: 31GB  199% of 15GB an a long,long indicator 

![goobox](https://user-images.githubusercontent.com/8937420/36051011-f14a774e-0de8-11e8-8be9-de627386feac.png)

**Comment by MeijeSibbel** [comment]
Thanks. We have to find a way to handle this. We set the max size to 15.654GB as its the Storj free tier and because its the stable amount of storage we tested it at. Unfortunately i don't see how we can check with libstorj if the user is on the free tier or not. Maybe we can just remove the percentage, scale the bar dynamically and only show the usage, not the percentage.

**Comment by MeijeSibbel** [comment]
I opened a issue for this.: https://github.com/Storj/libstorj/issues/420, maybe this is something @kaloyan-raev kan look into on the Storj side.

**Comment by MeijeSibbel** [comment]
This is fixed in the latest release, closing.
